### PR TITLE
#2672 Fix unexpected space when not followed by space

### PR DESCRIPTION
**Pull request by kylekatarnls**

### CODE REVIEW

**Comment by TimothyGu** [comment]
Can you please file a pull request against https://github.com/pugjs/pug/blob/master/packages/pug-lexer/index.js? We have moved this repo to a monorepo at pugjs/pug.

**Comment by kylekatarnls** [comment]
Sure

**Comment by kylekatarnls** [comment]
Hi again, were goes the expected json for unit tests?

**Comment by TimothyGu** [comment]
@kylekatarnls, https://github.com/pugjs/pug/blob/master/packages/pug-lexer/test/__snapshots__/index.test.js.snap

**Comment by kylekatarnls** [comment]
Thanks, here it is: https://github.com/pugjs/pug/pull/2695

**Pull request closed without merging**
