### PR TITLE
Overhaul indentation detection

### PR DESCRIPTION
**Pull request by TimothyGu**
- Record level of indentation in indent tokens rather than number of characters of indentation
- Support the first line of pipeless-text being indented (jadejs/jade#1588)
- Fixed comments-in-case.jade to be a legitimate test case

This breaks compatibility since previously "valid" code like:

``` jade
html
  body
   p Hello
```

is now regarded as invalid.

### CODE REVIEW

**Comment by TimothyGu** [comment]
Ping. I really want someone to look at this before I merge it.

**Comment by alubbe** [comment]
I do not feel confident that I fully understand this PR - but on the surface, it looks good.
Am I right in understanding that all children have to be indented by at least 2 spaces or 1 tab? I. e., 0 spaces -> sibling, 1 space -> invalid, 2+ spaces -> child?

**Comment by TimothyGu** [comment]
> Am I right in understanding that all children have to be indented by at least 2 spaces or 1 tab?

No, 1 space works as well.

**Comment by alubbe** [comment]
Then what makes 

``` jade
html
  body
   p Hello
```

invalid? If I add another space before `p` it is valid again, right?

**Comment by TimothyGu** [comment]
Yes. It catches **inconsistent** cases, not when it is consistently one space.

**Comment by alubbe** [comment]
Do we have that information so that we could print that in the error message?
Something like "Inconsistent indentation, expected N spaces/tabs"?

**Comment by TimothyGu** [comment]
The error message looks like this:

```
Error: Jade:3
    1| html
    2|   body
  > 3|    p Hello

Inconsistent indentation
    at makeError (/home/timothy_gu/jade-error/index.js:27:13)
    at Lexer.error (/home/timothy_gu/jade-lexer/index.js:59:15)
    at Lexer.indent (/home/timothy_gu/jade-lexer/index.js:925:14)
    at Lexer.advance (/home/timothy_gu/jade-lexer/index.js:1086:15)
    at Lexer.getTokens (/home/timothy_gu/jade-lexer/index.js:1102:12)
    at internalLex (/home/timothy_gu/jade-lexer/index.js:14:42)
    at lex (/home/timothy_gu/jade-lexer/index.js:10:10)
    at repl:1:13
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:250:14)
```

I guess I can add an "expected" but that would be a bit confusing as it would sound like "inconsistent indentation: got 3 spaces, expected multiples of 2 spaces"

**Comment by alubbe** [comment]
In your case we could print "Inconsistent indentation, expected either 2 or 4 spaces".
Btw, are either of these valid?

``` jade
html
  body
      p Hello
```

``` jade
html
  body
      p Hello
    p World
```

**Comment by TimothyGu** [comment]
> "Inconsistent indentation, expected either 2 or 4 spaces".

0 spaces work too.

> Btw, are either of these valid?

Good catch. They shouldn't be but they are accepted. A even more serious case is:

``` jade
html
  body
      p Hello
    p World
  p from
p Timothy
```

which is interpreted as

``` jade
html
  body
    p Hello
  p World
  p from
p Timothy
```

But this PR doesn't change the behavior, as the file was already broken.

**Comment by alubbe** [comment]
Fair enough - but let's maybe think of adding this to some bug list somewhere ;)
Regarding the error message, I think an indentation of 3 clearly means you do not want 0, but either 2 or 4, i.e., the user added one space too little or too many. 

In a world where the above cases are ruled out we could always print `"Inconsistent indentation, expected either X or X+indent spaces"`, where X is `Math.floor(number of spaces / indent) * indent`. What do you think?

Also, what is the scope of this indent variable? File-wide? How does it interact with include's and extend's?

**Comment by TimothyGu** [comment]
> Also, what is the scope of this indent variable? File-wide?

Yes, this is the lexer.

> Regarding the error message, I think an indentation of 3 clearly means you do not want 0, but either 2 or 4, i.e., the user added one space too little or too many.

I prefer not to guess what the user's intentions are.

> How does it interact with include's and extend's?

It doesn't.

How about these:

```
Error: Jade:3
    1| html
    2|   body
  > 3|    p Hey

Inconsistent indentation. Expected multiples of 2 spaces/tabs, got 3 spaces/tabs.

Error: Jade:4
    1| html
    2|   body
  > 3|       p Hey

Inconsistent indentation. Expected 4 spaces/tabs, got 6 spaces/tabs.

Error: Jade:4
    2|   body
    3|     p.
  > 4|      a

Inconsistent indentation. Expected multiples of 2 spaces/tabs, got 5 spaces/tabs.
```

**Comment by alubbe** [comment]
Like it a lot. From my code reading and the tests (old and new) it seems good, but maybe someone with better knowledge of the rest of the code wants to take a look as to how it was implemented?

**Comment by TimothyGu** [comment]
I just finished #16, which achieves the same goals but without the indentation overhaul. The fact that #16 preserves compatibility is something to consider.

**Comment by TimothyGu** [comment]
Closing in favor of #16.

**Pull request closed without merging**
