### PR TITLE
using real JSON files in test/cases

### PR DESCRIPTION
**Pull request by lazytyper**
I've converted the json files into real ones, and using `require()` for reading them.

### CODE REVIEW

**Comment by TimothyGu** [comment]
Frankly, I don't see the point in this. Real JSON files just complicate things, enlarging the files while offering no advantages beyond the ability to use `require`.

**Comment by lazytyper** [comment]
Well, IDEs keep telling that there are invalid JSON files in the project.

**Comment by lazytyper** [comment]
For to proof that no tests are changed or removed,
that's the code I've used for converting:

``` javascript
var fs = require('fs'),
    assert = require('assert');

var files = fs.readdirSync('.');

files.forEach(function (file) {
    var m = file.match(/^(.*\.expected.json)$/);
    if (m) {
        try {
            var test = require('./' + file);
            assert(Array.isArray(test));
            return;
        } catch (e) {
            console.log("Invalid file: " + file);
            var lines = fs.readFileSync(file).toString().split('\n');
            var json = '[\n  ' + lines.join(',\n  ') + '\n]';
            try {
                JSON.parse(json);
                fs.writeFileSync(file, json);
            } catch(e) {
                console.log(json);
                throw e;
            }
            console.log("...converted");
        }
    }
});
```

**Comment by ForbesLindesay** [comment]
I'm fine with us doing this (no strong opinion either way). I originally went with new-line separated JSON because it was the easiest way to get one token per line.  If we are doing this though, I also want to make sure the output for the `.actual.json` files is updated to match.

**Comment by lazytyper** [comment]
I've just been discovered this: http://jsonlines.org/
You could keep the "jsonlines", but then rename the files to `.jsonl` ;)

**Comment by ForbesLindesay** [comment]
If GitHub and most text editors highlight that correctly out of the box, I'd be happy with it.

**Pull request closed without merging**
