### PR TITLE
remove each loop index generation

### PR DESCRIPTION
**Pull request by alubbe**
needed for https://github.com/jadejs/jade-code-gen/pull/1/files

### CODE REVIEW

**Comment by TimothyGu** [comment]
Just to make sure, this PR isn't ready for merging yet right?

**Comment by alubbe** [comment]
no, it's ready. it now removes all index variable name generation

**Comment by ForbesLindesay** [comment]
The failing test cases can be auto-updated using `node test/update-test-cases`.  I'll merge then do that.

**Comment by TimothyGu** [comment]
Oh okay never mind.

**Pull request merged**
